version: "3"

services:
  node:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./github.com.pub:/home/node/.ssh/known_hosts:ro
      - ..:/workspaces/openhab-scheduler:cached
    tty: true
